# Generated by Django 2.1.7 on 2019-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.PositiveIntegerField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='students')),
                ('program', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cv')),
                ('about', models.TextField()),
            ],
        ),
    ]
