# Generated by Django 2.1.7 on 2019-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
    ]
